# Generated by Django 4.2.7 on 2026-01-27 07:32

from django.db import migrations, models
import esign_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(upload_to='documents/', validators=[esign_app.models.validate_document_file]),
        ),
    ]
