# Generated by Django 4.2.7 on 2026-02-02 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0002_alter_document_original_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='Document for Signature', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('signed', 'Signed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esign_app.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
