# Generated by Django 4.2.7 on 2026-02-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0003_emaildocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailDocument',
        ),
    ]
