# Generated by Django 4.2.7 on 2026-02-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0005_useractivity_temporaryuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='document',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='TemporaryUser',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
