# Generated by Django 4.2.7 on 2026-02-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0006_remove_useractivity_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='esign_app.document'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to='esign_app.document'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to='esign_app.signature'),
        ),
    ]
